language: python
python:
  - "3.6"

install:
  - pip install -U pip

before_script:
  - pip install -r requirements.txt

script:
  - pytest /api/v1/tests.unit_tests/Test_place_order

# safelist
branches:
  only:
    - ft-build-v1
