language: python
python:
  - "3.6"

install:
  - pip install -U pip

before_script:
  - pip install -r requirements.txt

script:
  - python app/tests/v1/test_views.py

# safelist
branches:
  only:
    - ft-build-v1
