language: python
python:
  - "3.6"

install:
  - pip install -U pip

before_script:
  - pip install -r requirements.txt

script:
  - pytest

after_script:
  - coveralls

# safelist
branches:
  only:
    - ft-build-v1
